---
- name: Common Installation
  hosts: all
  become: true
  roles:
    - common

- name: Master Setup
  hosts: master
  become: true
  roles:
    - master

- name: Slave Setup
  hosts: slaves
  become: true
  roles:
    - slave