---
- name: Launch Machines
  hosts: localhost
  become: False
  vars_files:
    - "private_vars/config.yaml"
  roles:
    - machine

- name: Common Installation
  hosts: master, slaves
  become: True
  vars_files:
    - "private_vars/config.yaml"
  roles:
    - common

- name: Master Setup
  hosts: master
  become: True
  vars_files:
    - "private_vars/config.yaml"
  roles:
    - master

- name: Slave Setup
  hosts: slaves
  become: True
  vars_files:
    - "private_vars/config.yaml"
  roles:
    - slave