---
  - name: Get Slave EC2 Instance Information
    ec2_remote_facts:
      aws_access_key: "{{ aws_key_id }}"
      aws_secret_key: "{{ aws_key_secret }}"
      region: "{{ aws_region }}"
      filters: 
        instance-state-name: running
        "tag:ClusterName": "{{ spark_cluster_name }}"
    register: spark_machines

  - name: Terminate Cluster
    ec2:
      state: 'absent'
      aws_access_key: "{{ aws_key_id }}"
      aws_secret_key: "{{ aws_key_secret }}"
      region: "{{ aws_region }}"
      instance_ids: '{{ item.id }}'
    with_items: "{{ spark_machines.instances }}"